document.writeln(" <div id=\'top\'>");
document.writeln("    	<div id=\'topdiv\'>");
document.writeln("            <span style=\'float:right\'>");
document.writeln("           		<c:if test=\'${empty loginUser}\'>");
document.writeln("	                <a href=\'login.jsp\' id=\'a_top\'>登录</a>");
document.writeln("	                <li>|</li>");
document.writeln("	                <a href=\'register.jsp\' id=\'a_top\'>注册</a>");
document.writeln("           		</c:if>");
document.writeln("       			<c:if test=\'${not empty loginUser}\'>");
document.writeln("       				<a href=\'userAddress?flag=show\' id=\'a_top\'>${loginUser.username}</a>");
document.writeln("       				<li>|</li>");
document.writeln("       				<a href=\'userLogout.do\' id=\'a_top\'>注销</a>");
document.writeln("       				<li>|</li>");
document.writeln("       				<a href=\'getOrderList\' id=\'a_top\'>我的订单</a>");
document.writeln("       			</c:if>");
document.writeln("                <li>|</li>");
document.writeln("                <a href=\'\' id=\'a_top\'>消息通知</a>");
document.writeln("                <a href=\'${pageContext.request.contextPath}/getCart\' id=\'shorpcar\'>购物车</a>");
document.writeln("            </span>");
document.writeln("        </div>");
document.writeln(" </div>");
document.writeln("<div id=\'second\'>");
document.writeln("	    <a href=\'\' id=\'seimg\' style=\' margin-top:23px;\'><img id=\'logo\' src=\'image/logo_top.png\' width=\'55\' height=\'54\'/></a>");
document.writeln("        <a href=\'\' id=\'seimg\' style=\' margin-top:17px;\'><img id=\'gif\' src=\'image/yyymix.gif\' width=\'180\' height=\'66\' /></a>");
document.writeln("        <p id=\'goodsType\'>");
document.writeln("			<!-- 根据ajax 回调函数 填写数据 到此id中 -->");
document.writeln("        </p>");
document.writeln("       <form class=\'form-inline pull-right\' style=\'margin-top: 40px;margin-right: 10px;\'>");
document.writeln("		");
document.writeln("		  <div class=\'form-group\'>");
document.writeln("		    <input type=\'text\' class=\'form-control\' style=\'width: 400px\'  placeholder=\'搜索一下好东西...\'>");
document.writeln("		  </div>");
document.writeln("		  <button type=\'submit\' class=\'btn btn-warning\'><span class=\'glyphicon glyphicon-search\'></span>&nbsp;&nbsp;搜索</button>");
document.writeln("	  </form>");
document.writeln("</div>");
document.writeln(" <script type=\'text/javascript\'>");
document.writeln("     $(document).ready(function(){");
document.writeln("         $.ajax({");
document.writeln("             url:\'${pageContext.request.contextPath}/goodsTypeAjax\',");
document.writeln("             method:\'get\',");
document.writeln("             success:function(data){");
document.writeln("                 var list = JSON.parse(data);");
document.writeln("                 for(var t in list){");
document.writeln("                     var a = $(\'<a href=\'${pageContext.request.contextPath}/getGoodsListByTypeId?typeid=\'+list[t].id+\'\'>\'+list[t].name+\'</a>\');");
document.writeln("                     $(\'#goodsType\').append(a);");
document.writeln("                 }");
document.writeln("             },");
document.writeln("             error:function(){");
document.writeln("                 //alert(\'失败\');");
document.writeln("             }");
document.writeln("         })");
document.writeln("     })");
document.writeln(" </script>");